services:
  frontend:
    container_name: hopeful-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://app:8080
    restart: unless-stopped

networks:
  default:
    external:
      name: hopeful-network
