import { LoadingProvider } from '@/providers/LoadingProvider';
import type { Metadata } from 'next';
import { Barlow, Geist, Geist_Mono } from 'next/font/google';
import Header, { Role } from './components/Header';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const barlow = Barlow({
  variable: '--font-barlow',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${barlow.variable} antialiased`}
      >
        <LoadingProvider>
          <Header role={Role.USER} />
          {children}
        </LoadingProvider>
      </body>
    </html>
  );
}
