name: CI - Feature & Fix Branches

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches:
      - dev
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js com cache de npm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # 3. Instalar dependências
      - name: Install dependencies
        run: npm ci

      # 4. Rodar lint
      - name: Lint code
        run: npm run lint

      # 5. Checar formatação com Prettier
      - name: Check code format
        run: npx prettier --check .

      # 6. Build Next.js
      - name: Build project
        run: npm run build

      # 7. Start Next.js (opcional, valida runtime)
      - name: Start Next.js in background
        run: npm run start &
