name: CI - Build & Lint

on:
  push:
    branches: ['**']   # roda em qualquer branch
  pull_request:
    branches: ['**']   # dispara para PRs de qualquer branch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js com cache do npm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # 3. Instalar dependências
      - name: Install dependencies
        run: npm ci

      # 4. Rodar lint
      - name: Lint code
        run: npm run lint

      # 5. Build Next.js
      - name: Build project
        run: npm run build
